const resList = [
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '358060',
      name: 'Momo Nation Cafe',
      uuid: '68b24be9-b431-46c9-a31e-7031b6c5e73c',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 'd3storg3ubbsaunesven',
      cuisines: ['Chinese', 'Snacks', 'Beverages'],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 41,
      minDeliveryTime: 41,
      maxDeliveryTime: 41,
      slaString: '41 MINS',
      lastMileTravel: 0.30000001192092896,
      slugs: {
        restaurant: 'momo-nation-cafe-hajipur-hajipur',
        city: 'patna',
      },
      cityState: '79',
      address:
        'RAJESHWER PLAZA,  NEAR HP PETROL PUMP DAK BANGLOW ROAD  HAJIPUR, Vaishali, Bihar-844101',
      locality: 'Ramdayalu Nagar - Hajipur Road',
      parentId: 4157,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.3 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '10% OFF',
        subHeader: 'UPTO ₹40',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '358060',
        deliveryTime: 41,
        minDeliveryTime: 41,
        maxDeliveryTime: 41,
        lastMileTravel: 0.30000001192092896,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.4',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '580239',
      name: 'Momomia Love In Every Bite',
      uuid: '722fab49-d823-4932-964d-399a4d4c89bb',
      city: '79',
      area: 'Adalpur',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: 'hbgnjdpig41kxbzhecfj',
      cuisines: ['Chinese', 'Fast Food', 'Snacks'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 24,
      minDeliveryTime: 24,
      maxDeliveryTime: 24,
      slaString: '24 MINS',
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant: 'momomia--love-in-every-bite-rajendra-chowk-rajendra-chowk',
        city: 'patna',
      },
      cityState: '79',
      address:
        'MANJU COMPLEX,BAGHMALI HAJIPUR,DISTRICT VAISHALI,BIHAR-844101,ANWARPUR,HAJIPUR,VAISHALI,BIHAR-844101',
      locality: 'Anjaanpeer Chowk',
      parentId: 232865,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.4 kms',
      hasSurge: false,
      sla: {
        restaurantId: '580239',
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '--',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '722393',
      name: 'BUDDHA VIHAR RESTAURANT',
      uuid: 'c0b3391e-152b-4229-ab8e-cead08ab4904',
      city: '79',
      area: 'HAJIPUR PATNA',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: 'b7462e8bca363cafdc31998a5bb0e7d7',
      cuisines: ['Chinese', 'Snacks'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: '28 MINS',
      lastMileTravel: 0.30000001192092896,
      slugs: {
        restaurant: 'buddha-vihar-restaurant-rajendra-chowk-rajendra-chowk',
        city: 'patna',
      },
      cityState: '79',
      address:
        'BINOD KUMAR S/O- RAGHUNATH PRASAD AT- 1st FLOOR, RAJESHWAR PLAZA GANDHI CHOWK NEAR PETROL PUMP HAJIPUR ,Hajipur,Vaishali,Bihar-844101',
      locality: 'Rajeshwar Plaza',
      parentId: 430153,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.3 kms',
      hasSurge: false,
      sla: {
        restaurantId: '722393',
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 0.30000001192092896,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '--',
      totalRatings: 0,
      new: true,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '346951',
      name: 'My first flight restaurant',
      uuid: 'b426528a-70f5-4198-86bf-b0a8f1b67a81',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 'ptjw66dccecvvfhg2vbn',
      cuisines: ['Chinese', 'Indian'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: '35 MINS',
      lastMileTravel: 0.699999988079071,
      slugs: {
        restaurant: 'my-first-flight-restaurant-hajipur-hajipur',
        city: 'patna',
      },
      cityState: '79',
      address: 'seeta chowk, bagmali hajipur Bihar',
      locality: 'Ashiyana Colony',
      parentId: 142448,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      sla: {
        restaurantId: '346951',
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 0.699999988079071,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.7',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '469627',
      name: 'Elite Family Choice Restaurant',
      uuid: '761b000e-132e-4d6d-ab74-8bb3cfeb72a7',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: '500+ ratings',
      cloudinaryImageId: 'hbqpkzsjudnhymgwzd7d',
      cuisines: ['North Indian', 'Chinese'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      slaString: '26 MINS',
      lastMileTravel: 0.699999988079071,
      slugs: {
        restaurant:
          'elite-family-choice-restaurant-rajendra-chowk-rajendra-chowk',
        city: 'patna',
      },
      cityState: '79',
      address: 'CINEMA ROAD, HAJIPUR, VAISHALI, BIHAR',
      locality: 'Cinema Road',
      parentId: 282287,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '20% OFF',
        subHeader: 'UPTO ₹50',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '469627',
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        lastMileTravel: 0.699999988079071,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.0',
      totalRatings: 500,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '497293',
      name: 'Brunch Italino',
      uuid: '836f425a-e76d-4a22-8d8a-16258709a204',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 'bwq7864odqj5upviagvs',
      cuisines: ['Bakery', 'Desserts', 'Italian-American'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 22,
      minDeliveryTime: 22,
      maxDeliveryTime: 22,
      slaString: '22 MINS',
      lastMileTravel: 0.5,
      slugs: {
        restaurant: 'brunch-italino-rajendra-chowk-rajendra-chowk',
        city: 'patna',
      },
      cityState: '79',
      address: 'DAK BANGLA ROAD , HAJIPUR',
      locality: 'Rajendra Chowk',
      parentId: 50561,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.5 kms',
      hasSurge: false,
      sla: {
        restaurantId: '497293',
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        lastMileTravel: 0.5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '2.4',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '582660',
      name: 'Grill Inn',
      uuid: '7b20f309-5fbb-43e8-a5f8-017ade5052cc',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: 'df8lkjqf7ezdz0rcz6ss',
      cuisines: ['Italian', 'Fast Food', 'Snacks'],
      tags: [],
      costForTwo: 15000,
      costForTwoString: '₹150 FOR TWO',
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      slaString: '29 MINS',
      lastMileTravel: 0.5,
      slugs: {
        restaurant: 'grill-inn-rajendra-chowk-rajendra-chowk',
        city: 'patna',
      },
      cityState: '79',
      address: 'Dakbangla Road , Infront of Monginis Cake Shop , Hajipur',
      locality: 'Dakbangla Road',
      parentId: 432,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.5 kms',
      hasSurge: false,
      sla: {
        restaurantId: '582660',
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        lastMileTravel: 0.5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '--',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '521417',
      name: 'Bun On Bun',
      uuid: '66ec09d1-5cff-4b9d-b5fa-810560656f04',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: '20+ ratings',
      cloudinaryImageId: 'iyiex9grsgffc1txdqlc',
      cuisines: ['Fast Food', 'Snacks', 'Beverages'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 37,
      minDeliveryTime: 37,
      maxDeliveryTime: 37,
      slaString: '37 MINS',
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: 'bun-on-bun-hajipur-hajipur',
        city: 'patna',
      },
      cityState: '79',
      address:
        'Prem Shukla market, Cinema Rd, yadav chowk, Hajipur, Bihar 844101, India',
      locality: 'Mishra Colony',
      parentId: 311154,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      sla: {
        restaurantId: '521417',
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.1',
      totalRatings: 20,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '209509',
      name: 'Shubhraj Sweets',
      uuid: 'cbc02dba-3084-4b98-ba85-072345e3485a',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 'fvruc3gabk5xek6tyojr',
      cuisines: ['Snacks', 'Sweets'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 24,
      minDeliveryTime: 24,
      maxDeliveryTime: 24,
      slaString: '24 MINS',
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: 'shubhraj-sweets-hajipur-hajipur',
        city: 'patna',
      },
      cityState: '79',
      address:
        'Shubhraj Sweets, Marai Road, JP Colony, Shahi colony, Hajipur, Bihar, India',
      locality: 'Shahi Colony',
      parentId: 187403,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      sla: {
        restaurantId: '209509',
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.5',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '487583',
      name: 'Kathi Junction',
      uuid: '7784aa5a-8da9-4dbe-be84-bda6ab8018a3',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: '50+ ratings',
      cloudinaryImageId: 'f0jgpc4tbaybnngkfdrc',
      cuisines: ['Snacks', 'Chinese', 'Burgers', 'Fast Food'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 27,
      minDeliveryTime: 27,
      maxDeliveryTime: 27,
      slaString: '27 MINS',
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: 'kathi-junction-rajendra-chowk-rajendra-chowk',
        city: 'patna',
      },
      cityState: '79',
      address:
        'Shop No-02, Palika Bazar, Opposite National Cinema Hall, cinema road, Hajipur',
      locality: 'Rajendra Chowk',
      parentId: 1935,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.8 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '10% OFF',
        subHeader: 'ABOVE ₹149',
        discountTag: 'FLAT DEAL',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '487583',
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.7',
      totalRatings: 50,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '224954',
      name: 'Barbecue Live',
      uuid: '677a3c5f-9d8d-4b34-9252-31b1ba6d6a6b',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'gxuskonfhcjckzb3axmo',
      cuisines: ['Biryani', 'Indian', 'North Indian'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 47,
      minDeliveryTime: 47,
      maxDeliveryTime: 47,
      slaString: '47 MINS',
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant: 'barbecue-live-hajipur-hajipur',
        city: 'patna',
      },
      cityState: '79',
      address: 'DANKBUNGLOW ROAD, HAJIPUR',
      locality: 'Lower Dakbungloow Road',
      parentId: 41789,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.8 kms',
      hasSurge: false,
      sla: {
        restaurantId: '224954',
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.4',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '730309',
      name: 'F M L CAFE & RESTAURANT',
      uuid: '6bbb3d18-7052-41e3-8add-aa2d5973dcbd',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: '924ad2de4296f1c213c16f49dfcdfb13',
      cuisines: ['North Indian', 'Chinese', 'Snacks'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: '39 MINS',
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: 'f-m-l-cafe-&-restaurant-hajipur-hajipur',
        city: 'patna',
      },
      cityState: '79',
      address:
        '1st Floor, Dusyant Kanan Plaza, New  Dakbanglow Road, Near Vermasen Bharat  Petrol Pump, Hajipur, Vaishali, Bihar-844101',
      locality: 'New Dakbanglow Road',
      parentId: 433980,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      sla: {
        restaurantId: '730309',
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '--',
      totalRatings: 0,
      new: true,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '683840',
      name: 'Asli Bhatrat Bakery',
      uuid: '05d9e111-5970-4ef4-9c36-8793aa41fcfa',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: '32a00a73fcf2b8d876e32fb78ba5297e',
      cuisines: ['Bakery'],
      tags: [],
      costForTwo: 60000,
      costForTwoString: '₹600 FOR TWO',
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      slaString: '30 MINS',
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant: 'asli-bhatrat-bakery-hajipur-hajipur',
        city: 'patna',
      },
      cityState: '79',
      address:
        'IMAM AZAM, S/O- MOHAMMAD HASAN, AT- STATION ROAD ANWARPUR, HAJIPUR, VAISHALI, BIHAR-844101',
      locality: 'Station Road',
      parentId: 408105,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.8 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '20% OFF',
        subHeader: 'UPTO ₹50',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '683840',
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '--',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '731459',
      name: 'Biryani Haveli',
      uuid: 'f2de6960-d7db-4e30-a2f4-1c859e36c1e1',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: 'be2bfa3b5dde1e71b41144e9b62878a9',
      cuisines: ['Biryani', 'Kebabs'],
      tags: [],
      costForTwo: 50000,
      costForTwoString: '₹500 FOR TWO',
      deliveryTime: 27,
      minDeliveryTime: 27,
      maxDeliveryTime: 27,
      slaString: '27 MINS',
      lastMileTravel: 1,
      slugs: {
        restaurant: 'biryani-haveli-hajipur-hajipur',
        city: 'patna',
      },
      cityState: '79',
      address:
        'MAA KALI BHAWAN,DAK BANGLOW ROAD,ANWARPUR,HAJIPUR,HAJIPUR,VAISHALI,BIHAR-844101',
      locality: 'Dak Banglow Road',
      parentId: 46733,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1 kms',
      hasSurge: false,
      sla: {
        restaurantId: '731459',
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '--',
      totalRatings: 0,
      new: true,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '736414',
      name: 'My Second Wife Restaurant',
      uuid: '58e4a3c1-b7d9-466e-a116-3d860f3e70a4',
      city: '79',
      area: 'Hajipur',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: '63748b674cd021f43b25a425cd8dcc1b',
      cuisines: ['North Indian', 'Chinese'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 41,
      minDeliveryTime: 41,
      maxDeliveryTime: 41,
      slaString: '41 MINS',
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: 'my-second-wife-restaurant-hajipur-hajipur',
        city: 'patna',
      },
      cityState: '79',
      address:
        'KUNDAN KUMAR S/O - ANIL RAY AT- SITA  CHOWK BAGMALI HAJIPUR, Hajipur, Vaishali,  Bihar-844101',
      locality: 'Sita Chowk',
      parentId: 436903,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2100,
        message: '',
        title: 'Delivery Charge',
        amount: '2100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.8 kms',
      hasSurge: false,
      sla: {
        restaurantId: '736414',
        deliveryTime: 41,
        minDeliveryTime: 41,
        maxDeliveryTime: 41,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '--',
      totalRatings: 0,
      new: true,
    },
    subtype: 'basic',
  },
]

export default resList
